-- Run this in your Supabase SQL Editor to set up the necessary tables

-- Create a table for transactions
create table transactions (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  title text not null,
  amount numeric not null,
  type text check (type in ('income', 'expense')) not null,
  category text not null,
  note text,
  date timestamp with time zone default timezone('utc'::text, now()) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Set up Row Level Security (RLS)
alter table transactions enable row level security;

-- Create policy to allow users to view their own transactions
create policy "Users can view their own transactions"
  on transactions for select
  using ( auth.uid() = user_id );

-- Create policy to allow users to insert their own transactions
create policy "Users can insert their own transactions"
  on transactions for insert
  with check ( auth.uid() = user_id );

-- Create policy to allow users to update their own transactions
create policy "Users can update their own transactions"
  on transactions for update
  using ( auth.uid() = user_id );

-- Create policy to allow users to delete their own transactions
create policy "Users can delete their own transactions"
  on transactions for delete
  using ( auth.uid() = user_id );
